name: "Cache Node and NPM Dependencies"
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: "NodeJS version to use"
    default: "20.x"
    required: false
  working-dir:
    description: "The working directory of the application"
    default: $GITHUB_WORKSPACE
  target-env:
    description: "Target env input"
    default: dev
    required: false
runs:
  using: composite
  steps:
    - name: "Setup NodeJS version ${{inputs.node-version}}"
      uses: actions/setup-node@v4
      with:
        node-version: "${{inputs.node-version}}"
    - name: "Check pwd"
      shell: bash
      run: pwd
    - name: "Cache dependencies"
      id: cache
      uses: actions/cache@v4
      with:
        key: "${{inputs.target-env}}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}"
        path: "${{inputs.working-dir}}/node-modules"
    - name: "Install dependencies"
      if: "${{steps.cache.outputs.cache-hit != 'true'}}"
      shell: bash
      run: "${{inputs.target-env != 'dev' && npm ci || npm ci --ommit=dev}}"
      working-directory: "${{inputs.working-dir}}"

