name: "02 - Workflow Events"
on: 
    schedule:
      - cron: 51 11 * * *
    push:
    pull_request:
    workflow_dispatch:
jobs:
  echo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Show the trigger"
        run: |
              echo "Event is: ${{github.event_name}}"

