name: "02 - Workflow Events"
on: 
    - push
    - pull_request
jobs:
  echo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Show the trigger"
        run: echo "Event is: ${{ github.event_name }}"

