name: "05 - 2 - Event Filters and Activity Types"
on:
    workflow_dispatch:
      
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo PR when closed"
              run: echo "echo PR when closing"