name: "09 - Using Functions"
on:
    pull_request:
    workflow_dispatch: 
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
          - name: "Print PR title"
            run: |
                 echo "PR title: ${{github.event.pull_request.title}}"
          - name: "Print PR labels"
            run: | 
                 echo "PR label in json format: ${{tojson(github.event.pull_request.labels)}}"
          - name: "Bug step"
            env:
                title: "${{github.event.pull_request.title}}"
            if: failure() && contains("${{env.title}}",'fix')
            run: echo "This is a bug"
          - name: "Sleep step"
            run: sleep 20
          - name: "Failing step"
            run: exit 1
          - name: "I will be skipped"
            if: success()
            run: echo "I will print if previous steps succeed."
          - name: "I will execute if previous failure"
            if: failure()
            run: echo "I will print if any previous step fails."
          - name: "I will execute if not cancelled"
            if: (!cancelled())
            run: echo "I will always print, except when the workflow is cancelled."
          - name: "I will execute when cancelled"
            if: cancelled()
            run: echo "Workflow cancelled"

    
