name: "11 - Working with Inputs"
on:
    workflow_dispatch: 
        inputs:
          dry-run:
            description: "Dry run input"
            type: boolean
            default: false
          target:
            description: "Target input"
            required: true
          tag:
            description: "Tag choice input"
            type: choice
            options:
              - v1
              - v2
              - v3
            default: v3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: echo "Building from tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    needs:
        - build
    environment: "${{inputs.target}}"
    if: ${{!inputs.dry-run}}
    steps:
      - name: "Deploy"
        run: echo "Deploying to ${{inputs.target}}"
            
