name: "12 - Working with Outputs"
on: 
    workflow_dispatch:
      inputs:
        build-status:
            description: "input for wf12"
            type: choice
            options:
              - success
              - failure
            default: success
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: "${{steps.build.outputs.status}}"
      output1: "${{steps.build.outputs.output1}}"
      output2: "${{steps.build.outputs.output2}}"
    steps:
      - name: "Print GITHUB_OUTPUT path"
        run: |
              echo "Print environment: $GITHUB_OUTPUT"
      - name: "Build"
        id: build
        run: |
             echo "status=${{inputs.build-status}}" >>$GITHUB_OUTPUT
             cat $GITHUB_OUTPUT
      - name: "Step with mistake"
        run: |
             echo "output1=val1" >>$GITHUB_OUTPUT
             echo "output2=val2" >>$GITHUB_OUTPUT
             cat $GITHUB_OUTPUT  
  deploy:
    runs-on: ubuntu-latest
    needs:
        - build
    steps:
      - name: "Deploy"
        run: echo "Deploying"
        if: ${{needs.build.outputs.build-status == 'success'}}
      - name: "Print Outputs"
        run: |
             echo "Output from build job: ${{needs.build.outputs.output1}}"

