name: "13 - Using Caching"
on:
    workflow_dispatch:
      inputs:
        use-cache:
            description: "Whether to execute cache step"
            type: boolean
            default: true
        node-version:
          description: "Node version parameter"
          type: choice
          options:
            - '18.x'
            - '20.x'
            - '21.x'
          default: '20.x'
jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./04-using-actions/react-app
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version: "${{inputs.node-version}}"
      - name: "Download cached dependencies"
        id: "cache"
        uses: "actions/cache@v3"
        with:
          key: "deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}"
          path: "13-caching/react-app/node_modules"
        if: ${{inputs.use-cache}}
      - name: "Install node dependencies"
        run: npm ci
        if: ${{steps.cache.outputs.cache.cache-hit == 'true'}}
      - name: "Install npm"
        run: npm install
      - name: "Run tests"
        run: |
              pwd  
              npm run test
      - name: "Building"
        run: npm run build
      - name: "Deploy to non prod"
        run: echo "Deploying to nonprod"
          

    
