name: "13 - Using Caching"
on:
    workflow_dispatch:
      inputs:
        use-cache:
            description: "Whether to execute cache step"
            type: boolean
            default: true
        node-version:
          description: "Node version parameter"
          type: choice
          options:
            - '18.x'
            - '20.x'
            - '21.x'
          default: '20.x'
jobs:
  build:
    runs-on: "ubuntu-latest"
    needs: install-deps
    defaults:
      run:
        working-directory: ./04-using-actions/react-app
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version: "${{inputs.node-version}}"
      - name: "Download cached dependencies"
        id: "cache"
        uses: "actions/cache@v3"
        with:
          #key: "deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}"
          key: ${{needs.install-deps.outputs.deps-cache-key}}
          path: "13-caching/react-app/node_modules"
      - name: "Install node dependencies"
        run: npm ci
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
      - name: "Install npm"
        run: npm install
      - name: "Run tests"
        run: |
              pwd  
              npm run test
      - name: "Building"
        run: npm run build
      - name: "Deploy to non prod"
        run: echo "Deploying to nonprod"
  
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04-using-actions/react-app
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "Setup Node"  
        uses: actions/setup-node@v4
        with:
          node-version: "${{inputs.node-version}}"
      - name: "Calculate cache key"
        id: "cache-key"
        run: |
             echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json')}}" > $GITHUB_OUTPUT
      - name: "Download cached dependencies" 
        uses: actions/cache@v3
        with:
          key: "${{steps.cache-key.outputs.CACHE_KEY}}" 
          path: "13-caching/react-app/node_modules"
        if: ${{inputs.use-cache}}
      - name: "Install dependencies"
        run: npm ci
        if: ${{steps.cache-key.outputs.cache-hit != 'true'}}
  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: ./04-using-actions/react-app
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "${{inputs.node-version}}"
      - name: "Download cached dependencies"
        uses: actions/cache@v3
        with:
          key: "${{needs.install-deps.outputs.deps-cache-key}}"
          path: "13-caching/react-app/node_modules"
      - name: "Install npm"
        run: npm install
      - name: "Testing"
        run: npm test
      - name: "Linting"  
        run: echo "Linting"
      
      
      
          

    
