name: "17 - 1 - Custom Actions - Composite"
on: 
    workflow_dispatch:
      inputs:
        target-env:
            description: "Input choice"
            type: choice
            options:
              - dev
              - prod
run-name: "17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}"
env: 
  working-dir: "./04-using-actions/react-app"
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: "${{env.working-dir}}"   
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node and NPM Dependencies"
        uses: "./.github/actions/composite-cache-deps"
        with:
            working-dir: "."
      - name: "Test"
        run: npm run test
      - name: "Build"
        run: npm run build
