name: "17 - 3 - Custom Actions - Docker"
on:
    workflow_dispatch: 
        inputs:
          url:
            description: "Url input"
            type: choice
            options:
              - "https://www.google.com"
              - "https://www.m.com"
          max_trials:
            description: "Maximum trials until action fails"
            default: '10'
            required: false
          delay:
            description: "Delay in seconds between trials"
            default: '5'
            required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Ping url code"
        uses: ./.github/actions/docker-ping-url
        with: 
            url: "${{inputs.url}}"
            max_trials: "${{inputs.max_trials}}"
            delay: "${{inputs.delay}}"